[package]
name = "assemblylift-core-event"
version = "0.1.0"
authors = ["Daniel Cook <xlem@akkoro.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3.4"
lazy_static = "1.4.0"
indexmap = "1.3.2"
crossbeam-utils = "0.7.2"