[workspace]
members = [
    "backends/aws-lambda/host",
    "backends/aws-lambda/guest",
    "backends/aws-lambda/iomod",
    "backends/aws-lambda/iomod/guest",
    "core",
    "core/guest",
    "core/event",
    "core/event/guest"
]
exclude = [
    "examples/hello-world"
]
