[workspace]
members = [
    "providers/aws-lambda/host",
    "providers/aws-lambda/guest",
    "providers/generic-docker",
    "providers/kubelet",
    "providers/openfaas",
    "core",
    "core/guest",
    "core/guest/macros",
    "core/iomod",
    "core/iomod/guest",
    "core/io",
    "core/io/guest",
    "core/io/common",
    "cli"
]
