[package]
name = "assemblylift-awslambda-iomod-guest"
version = "0.1.0"
authors = ["Daniel Cook <xlem@akkoro.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.106"
assemblylift_core_event_guest = { package = "assemblylift-core-event-guest", path = "../../../../core/event/guest" }
