[package]
name = "assemblylift-cli"
version = "0.2.3"
description = "AssemblyLift command line interface"
authors = ["Akkoro and the AssemblyLift contributors <assemblylift@akkoro.io>"]
edition = "2018"
license-file = "../LICENSE.md"
repository = "https://github.com/akkoro/assemblylift"
readme = "README.md"
exclude = ["resources/**"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "asml"
path = "src/main.rs"

[dependencies]
toml = "0.5.6"
clap = "2.33.1"
handlebars = "3.0.1"
zip = "0.5.6"
serde = { version = "1.0.111", features = ["derive", "rc"] }
serde_json = "1.0.53"
path_abs = "0.5.0"
walkdir = "2.3.1"

[dependencies.reqwest]
version = "0.10.6"
features = ["blocking"]
