[package]
name = "assemblylift-cli"
version = "0.2.9"
description = "AssemblyLift command line interface"
authors = ["Akkoro and the AssemblyLift contributors <assemblylift@akkoro.io>"]
edition = "2018"
license-file = "../LICENSE.md"
repository = "https://github.com/akkoro/assemblylift"
readme = "README.md"
exclude = ["resources/**"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "asml"
path = "src/main.rs"

[dependencies]
toml = "0.5.8"
clap = "2.33.3"
handlebars = "3.5.2"
zip = "0.5.9"
serde = { version = "1.0.118", features = ["derive", "rc"] }
serde_json = "1.0.61"
path_abs = "0.5.0"
walkdir = "2.3.1"

wasmer = { git = "https://github.com/dotxlem/wasmer", branch="atomic_cell" }
wasmer-compiler = { git = "https://github.com/dotxlem/wasmer", branch="atomic_cell" }
wasmer-compiler-cranelift = { git = "https://github.com/dotxlem/wasmer", branch="atomic_cell" }
#wasmer-compiler-llvm = { git = "https://github.com/dotxlem/wasmer", branch="atomic_cell" }
wasmer-engine-native = { git = "https://github.com/dotxlem/wasmer", branch="atomic_cell" }

[dependencies.reqwest]
version = "0.10.10"
features = ["blocking"]
