[package]
name = "cli"
version = "0.1.0"
authors = ["xlem <xlem@akkoro.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "asml"
path = "src/main.rs"

[dependencies]
clap = "2.33.1"
