[package]
name = "assemblylift-core"
version = "0.1.0"
authors = ["Daniel Cook <xlem@akkoro.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossbeam-utils = "0.7.2"
lazy_static = "1.4.0"
wasmer-runtime = { git = "https://github.com/dotxlem/wasmer", branch="atomic_cell" }
wasmer-runtime-core = { git = "https://github.com/dotxlem/wasmer", branch="atomic_cell" }
assemblylift_core_event = { package = "assemblylift-core-event", path = "./event" }
