[package]
name = "assemblylift-core"
version = "0.1.0"
authors = ["Daniel Cook <xlem@akkoro.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasmer-runtime = { path = "../../../Forks/wasmer/lib/runtime" }
wasmer-runtime-core = { path = "../../../Forks/wasmer/lib/runtime-core" }
assemblylift_core_event = { package = "assemblylift-core-event", path = "./event" }
