[package]
name = "assemblylift-core"
version = "0.1.0"
authors = ["Daniel Cook <xlem@akkoro.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3"
wasmer-runtime = { version = "0.15.0", optional = true }

[features]
default = []

client = []
host = ["wasmer-runtime"]
