[package]
name = "assemblylift-core"
version = "0.1.1"
description = "AssemblyLift core library"
authors = ["Akkoro and the AssemblyLift contributors <assemblylift@akkoro.io>"]
edition = "2018"
license-file = "../LICENSE.md"
repository = "https://github.com/akkoro/assemblylift"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"
once_cell = "1.4.0"
tokio = "0.2.21"
crossbeam-utils = "0.7.2"

wasmer_runtime = { version = "0.1.1", package = "wasmer-runtime-asml-fork" }
wasmer_runtime_core = { version = "0.1.1", package = "wasmer-runtime-core-asml-fork" }

assemblylift-core-event-common = { version = "0.1.0", path = "./event/common" }
