[package]
name = "assemblylift-core"
version = "0.2.3"
description = "AssemblyLift core library"
authors = ["Akkoro and the AssemblyLift contributors <assemblylift@akkoro.io>"]
edition = "2018"
license-file = "../LICENSE.md"
repository = "https://github.com/akkoro/assemblylift"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"
once_cell = "1.4.0"
tokio = "0.2.21"
crossbeam-utils = "0.8"

wasmer = { git = "https://github.com/dotxlem/wasmer", branch="atomic_cell" }

assemblylift-core-io-common = { version = "0.2.0", path = "./io/common" }
assemblylift-core-iomod = { version = "0.2.1", path = "./iomod" }
