[package]
name = "assemblylift-awslambda-host"
version = "0.1.0"
authors = ["Daniel Cook <daniel@akkoro.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "bootstrap"
path = "src/main.rs"

[dependencies]
wasmer-runtime = { path = "../../../../../Forks/wasmer/lib/runtime" }
wasmer-runtime-core = { path = "../../../../../Forks/wasmer/lib/runtime-core" }
lazy_static = "1.4.0"
reqwest = { version = "0.10.4", features = ["blocking"] }
awsio = {package = "assemblylift-awslambda-iomod", path = "../iomod" }
assemblylift_core = { package = "assemblylift-core", path = "../../../core" }
