[package]
name = "assemblylift-awslambda-host"
version = "0.1.0"
authors = ["Daniel Cook <daniel@akkoro.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "bootstrap"
path = "src/main.rs"

[dependencies]
crossbeam-utils = "0.7.2"
wasmer-runtime = "0.16.2"
wasmer-runtime-core = "0.16.2"
lazy_static = "1.4.0"
reqwest = { version = "0.10.4", features = ["blocking"] }
awsio = {package = "assemblylift-awslambda-iomod", path = "../iomod" }
assemblylift_core = { package = "assemblylift-core", path = "../../../core" }
assemblylift_core_event = { package = "assemblylift-core-event", path = "../../../core/event" }
