[package]
name = "assemblylift-awslambda-host"
version = "0.1.2"
description = "AssemblyLift AWS Lambda runtime"
authors = ["Akkoro and the AssemblyLift contributors <assemblylift@akkoro.io>"]
edition = "2018"
license-file = "../../../LICENSE.md"
repository = "https://github.com/akkoro/assemblylift"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "bootstrap"
path = "src/main.rs"

[dependencies]
crossbeam-utils = "0.7.2"
wasmer_runtime = { version = "0.1.1", package = "wasmer-runtime-asml-fork" }
wasmer_runtime_core = { version = "0.1.1", package = "wasmer-runtime-core-asml-fork" }
lazy_static = "1.4.0"
once_cell = "1.4.0"
clap = "3.0.0-beta.1"
reqwest = { version = "0.10.4", features = ["blocking"] }
awsio = { version = "0.1.2", package = "assemblylift-awslambda-iomod", path = "../iomod" }
assemblylift_core = { version = "0.1.1", package = "assemblylift-core", path = "../../../core" }
assemblylift_core_event = { version = "0.1.1", package = "assemblylift-core-event", path = "../../../core/event" }
assemblylift_core_event_common = { version = "0.1.0", package = "assemblylift-core-event-common", path = "../../../core/event/common" }
