[package]
name = "assemblylift-awslambda-iomod"
version = "0.1.0"
authors = ["xlem <xlem@akkoro.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rusoto_core = { version = "0.42.0" }
rusoto_dynamodb = { version = "0.42.0" }
wasmer-runtime = { path = "../../../../../Forks/wasmer/lib/runtime" }
wasmer-runtime-core = { path = "../../../../../Forks/wasmer/lib/runtime-core" }
assemblylift_core = { package = "assemblylift-core", path = "../../../core"}
assemblylift_core_event = { package = "assemblylift-core-event", path = "../../../core/event" }
